Pull request #410: upd-all
Merge in GO/dnsproxy from upd-all to master

Squashed commit of the following:

commit b0657dc564cadd40c3c23a0cbf2d1597595d2d6e
Author: f.setrakov <f.setrakov@adguard.com>
Date:   Mon Nov 17 17:19:38 2025 +0300

    upstream: add todo

commit 6a6b295d5e1d9b6be61412d92c207ea1064110de
Author: f.setrakov <f.setrakov@adguard.com>
Date:   Mon Nov 17 16:47:41 2025 +0300

    all: upd-all

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -2,28 +2,26 @@
 
 set -e -f -u
 
-# This comment is used to simplify checking local copies of the script.
-# Bump this number every time a significant change is made to this
-# script.
+# This comment is used to simplify checking local copies of the script.  Bump
+# this number every time a significant change is made to this script.
 #
-# AdGuard-Project-Version: 4
+# AdGuard-Project-Version: 5
 
 # TODO(a.garipov): Add pre-merge-commit.
 
-# Only show interactive prompts if there a terminal is attached to
-# stdout.  While this technically doesn't guarantee that reading from
-# /dev/tty works, this should work reasonably well on all of our
-# supported development systems and in most terminal emulators.
+# Only show interactive prompts if there a terminal is attached to stdout.
+# While this technically doesn't guarantee that reading from /dev/tty works,
+# this should work reasonably well on all of our supported development systems
+# and in most terminal emulators.
 is_tty='0'
 if [ -t '1' ]; then
 	is_tty='1'
 fi
 readonly is_tty
 
-# prompt is a helper that prompts the user for interactive input if that
-# can be done.  If there is no terminal attached, it sleeps for two
-# seconds, giving the programmer some time to react, and returns with
-# a zero exit code.
+# prompt is a helper that prompts the user for interactive input if that can be
+# done.  If there is no terminal attached, it sleeps for two seconds, giving the
+# programmer some time to react, and returns with a zero exit code.
 prompt() {
 	if [ "$is_tty" -eq '0' ]; then
 		sleep 2
@@ -49,9 +47,9 @@ prompt() {
 	done
 }
 
-# Warn the programmer about unstaged changes and untracked files, but do
-# not fail the commit, because those changes might be temporary or for
-# a different branch.
+# Warn the programmer about unstaged changes and untracked files, but do not
+# fail the commit, because those changes might be temporary or for a different
+# branch.
 #
 # shellcheck disable=SC2016
 awk_prog='substr($2, 2, 1) != "." { print $9; } $1 == "?" { print $2; }'
@@ -65,8 +63,8 @@ if [ "$unstaged" != '' ]; then
 	prompt
 fi
 
-# Warn the programmer about temporary todos and skel FIXMEs, but do not
-# fail the commit, because the commit could be in a temporary branch.
+# Warn the programmer about temporary todos and skel FIXMEs, but do not fail the
+# commit, because the commit could be in a temporary branch.
 temp_todos="$(
 	git grep -e 'FIXME' -e 'TODO.*!!' -- ':!scripts/hooks/pre-commit' || :
 )"
@@ -80,18 +78,18 @@ fi
 verbose="${VERBOSE:-0}"
 readonly verbose
 
-if [ "$(git diff --cached --name-only -- '*.md' || true)" != '' ]; then
+if [ "$(git diff --cached --name-only -- '*.md' || :)" != '' ]; then
 	make VERBOSE="$verbose" md-lint
 fi
 
-if [ "$(git diff --cached --name-only -- '*.sh' || true)" != '' ]; then
+if [ "$(git diff --cached --name-only -- '*.sh' || :)" != '' ]; then
 	make VERBOSE="$verbose" sh-lint
 fi
 
-if [ "$(git diff --cached --name-only -- '*.md' '*.yaml' '*.yml' || true)" != '' ]; then
+if [ "$(git diff --cached --name-only -- '*.md' '*.yaml' '*.yml' || :)" != '' ]; then
 	make VERBOSE="$verbose" txt-lint
 fi
 
-if [ "$(git diff --cached --name-only -- '*.go' '*.mod' 'Makefile' || true)" != '' ]; then
+if [ "$(git diff --cached --name-only -- '*.go' '*.mod' 'Makefile' || :)" != '' ]; then
 	make VERBOSE="$verbose" go-os-check go-lint go-test
 fi
